#!/bin/bash

CXX="g++"
CXXFLAGS="-std=c++17 -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -Wpedantic -Wno-sign-compare -Wno-unused-function"
HDFLAGS="-I ./alglib"
LDFLAGS="-L/usr/local/lib -L. -L/usr/local/lib/Matplot++"
#  
# versione wsl notebook
#
LDLIBS="-Wl,--start-group -lmatplot -lsvdqr -lnodesoup -lpng -ltiff -lz -ljpeg -lm -Wl,--end-group"
#
# versione lab
#
# LDLIBS="-Wl,--start-group -lmatplot -lsvdqr -lm -Wl,--end-group"


SOURCES="fcn_all.cpp fcn_lib_calc.cpp"
HEADERS="fcn_lib_calc.h menu_config.h json.hpp"
TARGET="fcn_all"

# Verifica che i sorgenti esistano
for src in $SOURCES; do
    if [[ ! -f "$src" ]]; then
        echo "Errore: file sorgente mancante: $src"
        exit 1
    fi
done

echo "Compilazione in corso..."
$CXX $CXXFLAGS $HDFLAGS $LDFLAGS $SOURCES -o $TARGET $LDLIBS

if [[ $? -eq 0 ]]; then
    echo "Compilazione completata: ./$TARGET"
    ./$TARGET
else
    echo "Compilazione fallita!"
    exit 1
fi